import React from 'react';
import { 
  RegionalPerformanceItem, 
  CategoryPerformanceItem, 
  ProductRankingItem, 
  CustomerSegmentItem 
} from '../../types/businessIntelligence';
import { BIEngine } from '../../utils/analytics/biEngine';

interface ReportTableSectionProps {
  regions: RegionalPerformanceItem[];
  categories: CategoryPerformanceItem[];
  topProducts: ProductRankingItem[];
  bottomProducts: ProductRankingItem[];
  segments: CustomerSegmentItem[];
  topN: number;
  className?: string;
}

export const ReportTableSection: React.FC<ReportTableSectionProps> = ({
  regions,
  categories,
  topProducts,
  bottomProducts,
  segments,
  topN,
  className = ''
}) => {
  return (
    <div className={`space-y-6 ${className}`}>
      <div className="border-b border-slate-200/80 pb-2 dark:border-slate-800">
        <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100 uppercase tracking-wide">
          Multi-Dimensional Performance Tables (Top {topN})
        </h3>
        <p className="text-xs text-slate-500 dark:text-slate-400">
          Rankings and financial metrics generated by Analytics & BI Engines
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* Table 1: Regional Attainment */}
        {regions.length > 0 && (
          <div className="rounded-xl border border-slate-200/80 bg-white p-4 shadow-2xs dark:border-slate-800/90 dark:bg-slate-900/90 break-inside-avoid">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">
                Regional Performance & Scorecard
              </h4>
              <span className="text-[10px] font-mono text-slate-400">{regions.length} Operating Theaters</span>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-100 font-semibold text-slate-500 dark:border-slate-800">
                    <th className="py-2">Rank</th>
                    <th className="py-2">Region</th>
                    <th className="py-2 text-right">Sales</th>
                    <th className="py-2 text-right">Profit</th>
                    <th className="py-2 text-right">Margin</th>
                    <th className="py-2 text-right">Score</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-mono">
                  {regions.slice(0, topN).map((r) => (
                    <tr key={r.region}>
                      <td className="py-1.5 font-bold text-slate-400">#{r.rank}</td>
                      <td className="py-1.5 font-sans font-semibold text-slate-900 dark:text-slate-100">{r.region}</td>
                      <td className="py-1.5 text-right font-bold text-indigo-600 dark:text-indigo-400">{BIEngine.formatCurrency(r.sales)}</td>
                      <td className="py-1.5 text-right text-emerald-600 dark:text-emerald-400">{BIEngine.formatCurrency(r.profit)}</td>
                      <td className="py-1.5 text-right">{r.margin}%</td>
                      <td className="py-1.5 text-right font-bold text-slate-800 dark:text-slate-200">{r.performanceScore}/100</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Table 2: Category Dynamics */}
        {categories.length > 0 && (
          <div className="rounded-xl border border-slate-200/80 bg-white p-4 shadow-2xs dark:border-slate-800/90 dark:bg-slate-900/90 break-inside-avoid">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">
                Product Category Economics & Share
              </h4>
              <span className="text-[10px] font-mono text-slate-400">{categories.length} Categories</span>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-100 font-semibold text-slate-500 dark:border-slate-800">
                    <th className="py-2">Rank</th>
                    <th className="py-2">Category</th>
                    <th className="py-2 text-right">Sales</th>
                    <th className="py-2 text-right">Profit</th>
                    <th className="py-2 text-right">Margin</th>
                    <th className="py-2 text-right">Share</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-mono">
                  {categories.slice(0, topN).map((c) => (
                    <tr key={c.category}>
                      <td className="py-1.5 font-bold text-slate-400">#{c.rank}</td>
                      <td className="py-1.5 font-sans font-semibold text-slate-900 dark:text-slate-100">{c.category}</td>
                      <td className="py-1.5 text-right font-bold text-sky-600 dark:text-sky-400">{BIEngine.formatCurrency(c.sales)}</td>
                      <td className="py-1.5 text-right text-emerald-600 dark:text-emerald-400">{BIEngine.formatCurrency(c.profit)}</td>
                      <td className="py-1.5 text-right">{c.profitMargin}%</td>
                      <td className="py-1.5 text-right font-bold text-indigo-600 dark:text-indigo-400">{c.share}%</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Table 3: Top N Products */}
        {topProducts.length > 0 && (
          <div className="rounded-xl border border-slate-200/80 bg-white p-4 shadow-2xs dark:border-slate-800/90 dark:bg-slate-900/90 break-inside-avoid">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">
                Top {topN} Revenue Generating Products
              </h4>
              <span className="text-[10px] font-mono text-emerald-600 font-semibold">Volume Leaders</span>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-100 font-semibold text-slate-500 dark:border-slate-800">
                    <th className="py-2">Rank</th>
                    <th className="py-2">Product Name</th>
                    <th className="py-2 text-right">Sales Volume</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-mono">
                  {topProducts.slice(0, topN).map((p) => (
                    <tr key={p.product}>
                      <td className="py-1.5 font-bold text-slate-400">#{p.rank}</td>
                      <td className="py-1.5 font-sans font-medium text-slate-900 dark:text-slate-100">{p.product}</td>
                      <td className="py-1.5 text-right font-bold text-indigo-600 dark:text-indigo-400">{p.formattedValue}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Table 4: Bottom N Products (Focus Areas) */}
        {bottomProducts.length > 0 && (
          <div className="rounded-xl border border-slate-200/80 bg-white p-4 shadow-2xs dark:border-slate-800/90 dark:bg-slate-900/90 break-inside-avoid">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">
                Bottom {topN} Products Requiring Pricing Review
              </h4>
              <span className="text-[10px] font-mono text-amber-600 font-semibold">Margin Attention</span>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-100 font-semibold text-slate-500 dark:border-slate-800">
                    <th className="py-2">Rank</th>
                    <th className="py-2">Product Name</th>
                    <th className="py-2 text-right">Sales Volume</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-mono">
                  {bottomProducts.slice(0, topN).map((p) => (
                    <tr key={p.product}>
                      <td className="py-1.5 font-bold text-slate-400">#{p.rank}</td>
                      <td className="py-1.5 font-sans font-medium text-slate-900 dark:text-slate-100">{p.product}</td>
                      <td className="py-1.5 text-right text-slate-600 dark:text-slate-300">{p.formattedValue}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
